# Generated by Django 5.0.6 on 2024-08-14 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='thumbnail',
            field=models.ImageField(default='defaults/mouse.png', upload_to='services/'),
        ),
    ]
