# Generated by Django 5.0.6 on 2024-07-25 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SkillIcon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('icon_class', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('heading', models.CharField(blank=True, max_length=50, null=True)),
                ('skill_desc', models.TextField(blank=True, null=True)),
                ('logo_1', models.ImageField(blank=True, null=True, upload_to='skill_logo')),
                ('logo_2', models.ImageField(blank=True, null=True, upload_to='skill_logo')),
                ('logo_3', models.ImageField(blank=True, null=True, upload_to='skill_logo')),
                ('skill_txt', models.TextField()),
                ('order', models.PositiveIntegerField(blank=True, null=True)),
                ('icon_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='icon_1', to='about_me.skillicon')),
                ('icon_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='icon_2', to='about_me.skillicon')),
                ('icon_3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='icon_3', to='about_me.skillicon')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
