# Generated by Django 5.0.6 on 2024-08-14 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_me', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='heading',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='skill_desc',
        ),
    ]
