# Generated by Django 5.0.6 on 2024-07-25 07:54

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('un_read', 'Un-read'), ('read', 'Read'), ('contact', 'Contacted'), ('on_hold', 'On Hold'), ('follow_up', 'Follow-up'), ('confirm', 'Confirm'), ('cancelled', 'Cancelled')], default='un_read', max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=400)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True)),
                ('deadline', models.DateField(blank=True, default=datetime.date(2024, 8, 22), null=True)),
                ('message', models.TextField()),
                ('remark', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('is_active', models.BooleanField(default=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pricing.service')),
            ],
        ),
    ]
