# Generated by Django 5.0.6 on 2024-08-14 04:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='deadline',
            field=models.DateField(blank=True, default=datetime.date(2024, 9, 11), null=True),
        ),
    ]
