# Generated by Django 5.0.6 on 2024-07-25 07:54

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_photo', models.ImageField(blank=True, default='users/user-photo.jpg', upload_to='users/')),
                ('position', models.CharField(blank=True, max_length=50)),
                ('intro', models.TextField(blank=True)),
                ('mobile', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('website_url', models.URLField(blank=True, default='https://')),
                ('linkedin_url', models.URLField(blank=True, default='https://')),
                ('github_url', models.URLField(blank=True, default='https://')),
                ('stackoverflow_url', models.URLField(blank=True, default='https://')),
                ('twitter_url', models.URLField(blank=True, default='https://')),
                ('reddit_url', models.URLField(blank=True, default='https://')),
                ('facebook_url', models.URLField(blank=True, default='https://')),
                ('logo', models.ImageField(blank=True, default='users/user-logo.png', upload_to='users/')),
                ('fav_icon', models.ImageField(blank=True, default='users/fav-icon.png', upload_to='users/')),
                ('index_title', models.CharField(blank=True, max_length=254)),
                ('index_meta_kewords', models.TextField(blank=True)),
                ('short_desc', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member_id', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('profile_img', models.ImageField(blank=True, null=True, upload_to='developer_photo/')),
                ('mobile', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('nid', models.CharField(max_length=30)),
                ('passport', models.CharField(blank=True, max_length=30, null=True)),
                ('address', models.CharField(max_length=200)),
                ('nationality', models.CharField(blank=True, max_length=50, null=True)),
                ('religion', models.CharField(blank=True, max_length=50, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('blood', models.CharField(blank=True, max_length=6, null=True)),
                ('join_date', models.DateTimeField()),
                ('rejoin_date', models.DateTimeField(blank=True, null=True)),
                ('skill', models.TextField()),
                ('resume', models.FileField(default='resume.pdf', upload_to='developer_resume/')),
                ('portfolio_url', models.URLField(blank=True, default='https://www.yourdomain.com')),
                ('github_url', models.URLField(blank=True, default='https://www.github.com/')),
                ('linkedin_url', models.URLField(blank=True, default='https://www.linkedin.com/')),
                ('stackoverflow_url', models.URLField(blank=True, default='https://www.stackoverflow.com/')),
                ('reddit_url', models.URLField(blank=True, default='https://www.reddit.com/')),
                ('facebook_url', models.URLField(blank=True, default='https://www.facebook.com/')),
                ('intro', models.TextField(blank=True, default='I am ', null=True)),
                ('order', models.PositiveIntegerField(blank=True, null=True)),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gender', to='users.gender')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_role', to='users.role')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
