# Generated by Django 5.0.6 on 2024-08-14 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersetting',
            options={'verbose_name_plural': 'Site Settings'},
        ),
        migrations.AlterField(
            model_name='usersetting',
            name='logo',
            field=models.ImageField(blank=True, default='users/logo.jpg', upload_to='users/'),
        ),
    ]
