# Generated by Django 5.0.6 on 2024-07-25 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('review', 'Under Review'), ('testing', 'Testing'), ('updating', 'Updating'), ('pause', 'Pause'), ('maintenance', 'In Maintenance'), ('completed', 'Completed'), ('on_hold', 'On Hold'), ('cancelled', 'Cancelled'), ('archived', 'Archived')], default='pending', max_length=20)),
                ('budget', models.DecimalField(decimal_places=2, max_digits=12)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('intro', models.TextField()),
                ('client', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, default='hello@xxx.com', max_length=254, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(upload_to='projects')),
                ('order', models.PositiveIntegerField(blank=True, null=True)),
                ('remark', models.TextField(blank=True, default='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectCaseStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.ImageField(upload_to='projects/case_study')),
                ('industry', models.CharField(max_length=100)),
                ('employee', models.CharField(max_length=12)),
                ('website', models.URLField(default='https://', max_length=100)),
                ('short_desc', models.CharField(max_length=400)),
                ('overview', models.TextField()),
                ('challenge', models.TextField()),
                ('solution_txt', models.TextField()),
                ('solution_img1', models.ImageField(blank=True, null=True, upload_to='projects/case_study')),
                ('solution_img2', models.ImageField(blank=True, null=True, upload_to='projects/case_study')),
                ('result_txt', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='case_study', to='portfolio.project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectDeveloper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('join_date', models.DateField()),
                ('leave_date', models.DateField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(blank=True, null=True)),
                ('remark', models.TextField(blank=True, default='')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projec_dev_name', to='users.team')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_name', to='portfolio.project')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_role', to='users.role')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectRequirment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.PositiveIntegerField(blank=True, null=True)),
                ('project_case_study', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='requirments', to='portfolio.projectcasestudy')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('percent', models.CharField(default='20%', max_length=10)),
                ('up_or_down', models.CharField(default='up', max_length=10)),
                ('txt', models.TextField()),
                ('order', models.PositiveIntegerField(blank=True, null=True)),
                ('project_case_study', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='results', to='portfolio.projectcasestudy')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectTechnology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.PositiveIntegerField(blank=True, null=True)),
                ('project_case_study', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='technologies', to='portfolio.projectcasestudy')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('position', models.CharField(blank=True, max_length=255)),
                ('testimonial_type', models.CharField(choices=[('general', 'General'), ('project', 'Project Specific')], default='general', max_length=50)),
                ('comments', models.TextField()),
                ('image', models.ImageField(blank=True, default='defaults/user-icon.jpg', null=True, upload_to='users/testimonial')),
                ('order', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=False)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testimonials', to='portfolio.project')),
            ],
        ),
    ]
