# Generated by Django 5.0.6 on 2024-08-14 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectcasestudy',
            name='short_desc',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='projectcasestudy',
            name='solution_img1',
            field=models.ImageField(blank=True, default='defaults/default-img.jpg', null=True, upload_to='projects/case_study'),
        ),
        migrations.AlterField(
            model_name='projectcasestudy',
            name='solution_img2',
            field=models.ImageField(blank=True, default='defaults/default-img.jpg', null=True, upload_to='projects/case_study'),
        ),
        migrations.AlterField(
            model_name='projectcasestudy',
            name='website',
            field=models.URLField(blank=True, default='https://', max_length=100),
        ),
        migrations.AlterField(
            model_name='projectrequirment',
            name='project_case_study',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirments', to='portfolio.projectcasestudy'),
        ),
        migrations.AlterField(
            model_name='projectresult',
            name='project_case_study',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='portfolio.projectcasestudy'),
        ),
        migrations.AlterField(
            model_name='projectresult',
            name='up_or_down',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='projecttechnology',
            name='project_case_study',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technologies', to='portfolio.projectcasestudy'),
        ),
    ]
